
-- CREATE TABLE IF NOT EXISTS PROFESSOR(
--   ID INT PRIMARY KEY,
--   NOME VARCHAR(100) NOT NULL,
--   CPF CHAR(11) UNIQUE NOT NULL
--   );

-- CREATE TABLE if NOT EXISTS TURMA(
--   ID INT,
--   NUM INT,
--   DURACAO_DIAS INT,
--   ID_PROFESSOR INT,
--   PRIMARY KEY(ID, NUM),
--   CONSTRAINT fk_prof FOREIGN KEY(ID_PROFESSOR) REFERENCES PROFESSOR(ID)
--   );
--   \dt
--   \d TURMA
--   \d PROFESSOR

 CREATE TABLE IF NOT EXISTS FORNECEDOR(
   ID INT PRIMARY KEY,
   NOME VARCHAR(100) NOT NULL,
   CIDADE VARCHAR(30)  NOT NULL
   );
   
   CREATE TABLE IF NOT EXISTS PECA(
   ID INT PRIMARY KEY,
   NOME VARCHAR(100) NOT NULL,
   DESCRICAO TEXT  NOT NULL
   );
   
     CREATE TABLE IF NOT EXISTS VENDA(
   ID_FORNECEDOR INT,
   ID_PECA INT,
   DATA DATE NOT NULL,
   QUANTIDADE INT NOT NULL,
   CONSTRAINT fk_fornecedor FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(ID),
   CONSTRAINT fk_peca FOREIGN KEY(ID_PECA) REFERENCES PECA(ID)
   );
   
   ALTER TABLE fornecedor
   ADD COLUMN telefone CHAR(11);
   
   ALTER TABLE PECA
   ADD COLUMN PRECO INT;
   
   ALTER TABLE fornecedor
   DROP COLUMN CIDADE;
   
   \dt;
   \d fornecedor;
   \d PECA;
   \d VENDA;
   
